first commit1

diff --git a/contrib/snap/snapcraft.yaml b/contrib/snap/snapcraft.yaml
--- a/contrib/snap/snapcraft.yaml
+++ b/contrib/snap/snapcraft.yaml
@@ -1,9 +1,9 @@
-name: termucoin-core
+name: nerocash-core
 # Running 'snapcraft register <name>' is advised
 version: '1.14.6'
-summary: Reference client of Termucoin, a peer-to-peer digital currency like Bitcoin.
+summary: Reference client of Nerocash, a peer-to-peer digital currency like Bitcoin.
 description: |
-  Termucoin is a community-driven cryptocurrency that was Technology. The Termucoin Core software allows anyone to operate a node in the Termucoin blockchain networks and uses the Scrypt hashing method for Proof of Work. It is adapted from Bitcoin Core and other cryptocurrencies.
+  Nerocash is a community-driven cryptocurrency that was Technology. The Nerocash Core software allows anyone to operate a node in the Nerocash blockchain networks and uses the Scrypt hashing method for Proof of Work. It is adapted from Bitcoin Core and other cryptocurrencies.
 
 grade: stable
 confinement: strict
@@ -19,29 +19,29 @@ architectures:
 
 apps:
   d:
-    command: termucoind
+    command: nerocashd
     plugs: [home, removable-media, network, network-bind]
     environment:
-      # Override HOME so the datadir is located at ~/snap/termucoin-core/common/.termucoin/ instead of ~/snap/termucoin-core/current/.termucoin/, and each new version of the snap won't have a different data directory: https://docs.snapcraft.io/environment-variables/7983
+      # Override HOME so the datadir is located at ~/snap/nerocash-core/common/.nerocash/ instead of ~/snap/nerocash-core/current/.nerocash/, and each new version of the snap won't have a different data directory: https://docs.snapcraft.io/environment-variables/7983
       HOME: $SNAP_USER_COMMON
   qt:
-    command: desktop-launch termucoin-qt
+    command: desktop-launch nerocash-qt
     plugs: [home, removable-media, network, network-bind, desktop, x11, unity7]
     environment:
       HOME: $SNAP_USER_COMMON
       DISABLE_WAYLAND: 1
   cli:
-    command: termucoin-cli
+    command: nerocash-cli
     plugs: [home, removable-media, network]
     environment:
       HOME: $SNAP_USER_COMMON
   tx:
-    command: termucoin-tx
+    command: nerocash-tx
     plugs: [home, removable-media, network]
     environment:
       HOME: $SNAP_USER_COMMON
   test:
-    command: test_termucoin
+    command: test_nerocash
     plugs: [home, removable-media, network]
     environment:
       HOME: $SNAP_USER_COMMON
@@ -76,48 +76,48 @@ parts:
       - xdg-user-dirs
       - fcitx-frontend-qt5
 
-  termucoin-core:
+  nerocash-core:
     plugin: nil
     override-build: |
-      echo "This script is viewable at https://github.com/termucoin/termucoin/blob/master/contrib/snap/snapcraft.yaml"
+      echo "This script is viewable at https://github.com/nerocash/nerocash/blob/master/contrib/snap/snapcraft.yaml"
       echo "Downloading files..."
-      if [ "$SNAPCRAFT_ARCH_TRIPLET" = "i386-linux-gnu" ]; then # snap designates 32-bit as i386, but termucoin designates it as i686
+      if [ "$SNAPCRAFT_ARCH_TRIPLET" = "i386-linux-gnu" ]; then # snap designates 32-bit as i386, but nerocash designates it as i686
         BUILD_ARCH_TRIPLET=i686-pc-linux-gnu
       else
         BUILD_ARCH_TRIPLET=$SNAPCRAFT_ARCH_TRIPLET
       fi
-      wget https://github.com/termucoin/termucoin/releases/download/v${SNAPCRAFT_PROJECT_VERSION}/termucoin-${SNAPCRAFT_PROJECT_VERSION}-${BUILD_ARCH_TRIPLET}.tar.gz
-      wget https://github.com/termucoin/gitian.sigs/archive/refs/heads/master.tar.gz
+      wget https://github.com/nerocash/nerocash/releases/download/v${SNAPCRAFT_PROJECT_VERSION}/nerocash-${SNAPCRAFT_PROJECT_VERSION}-${BUILD_ARCH_TRIPLET}.tar.gz
+      wget https://github.com/nerocash/gitian.sigs/archive/refs/heads/master.tar.gz
       tar -xvf master.tar.gz
       echo "Verifying secure hash matches signed values..."
-      checksum=$(sha256sum termucoin-${SNAPCRAFT_PROJECT_VERSION}-${BUILD_ARCH_TRIPLET}.tar.gz)
-      if ! (grep -r $checksum * | grep termucoin-${SNAPCRAFT_PROJECT_VERSION}-${BUILD_ARCH_TRIPLET}.tar.gz); then
+      checksum=$(sha256sum nerocash-${SNAPCRAFT_PROJECT_VERSION}-${BUILD_ARCH_TRIPLET}.tar.gz)
+      if ! (grep -r $checksum * | grep nerocash-${SNAPCRAFT_PROJECT_VERSION}-${BUILD_ARCH_TRIPLET}.tar.gz); then
         echo "Secure hash not verified."
         return
       else
         echo "Secure hash verified."
       fi
-      tar -xvf termucoin-${SNAPCRAFT_PROJECT_VERSION}-${BUILD_ARCH_TRIPLET}.tar.gz
+      tar -xvf nerocash-${SNAPCRAFT_PROJECT_VERSION}-${BUILD_ARCH_TRIPLET}.tar.gz
       echo "Running tests..."
-      if ! (termucoin-${SNAPCRAFT_PROJECT_VERSION}/bin/test_termucoin); then
-        echo "Termucoin tests failed."
+      if ! (nerocash-${SNAPCRAFT_PROJECT_VERSION}/bin/test_nerocash); then
+        echo "Nerocash tests failed."
         return
       else
-        echo "Termucoin tests passed."
+        echo "Nerocash tests passed."
       fi
-      wget https://raw.githubusercontent.com/termucoin/termucoin/v${SNAPCRAFT_PROJECT_VERSION}/doc/release-notes.md
+      wget https://raw.githubusercontent.com/nerocash/nerocash/v${SNAPCRAFT_PROJECT_VERSION}/doc/release-notes.md
       cat release-notes.md
-      echo "Installing Termucoin Core..."
+      echo "Installing Nerocash Core..."
       echo "Version ${SNAPCRAFT_PROJECT_VERSION}"
-      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin termucoin-${SNAPCRAFT_PROJECT_VERSION}/bin/termucoind
-      if ! ([ "$BUILD_ARCH_TRIPLET" = "aarch64-linux-gnu" ]); then # there is no official termucoin-qt build on arm64
-        install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin termucoin-${SNAPCRAFT_PROJECT_VERSION}/bin/termucoin-qt
+      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin nerocash-${SNAPCRAFT_PROJECT_VERSION}/bin/nerocashd
+      if ! ([ "$BUILD_ARCH_TRIPLET" = "aarch64-linux-gnu" ]); then # there is no official nerocash-qt build on arm64
+        install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin nerocash-${SNAPCRAFT_PROJECT_VERSION}/bin/nerocash-qt
       fi
-      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin termucoin-${SNAPCRAFT_PROJECT_VERSION}/bin/termucoin-cli
-      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin termucoin-${SNAPCRAFT_PROJECT_VERSION}/bin/termucoin-tx
-      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin termucoin-${SNAPCRAFT_PROJECT_VERSION}/bin/test_termucoin
-      wget https://raw.githubusercontent.com/termucoin/termucoin/master/share/pixmaps/termucoin128.png
-      install -m 0644 -D -t $SNAPCRAFT_PART_INSTALL/share/pixmaps termucoin128.png
+      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin nerocash-${SNAPCRAFT_PROJECT_VERSION}/bin/nerocash-cli
+      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin nerocash-${SNAPCRAFT_PROJECT_VERSION}/bin/nerocash-tx
+      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin nerocash-${SNAPCRAFT_PROJECT_VERSION}/bin/test_nerocash
+      wget https://raw.githubusercontent.com/nerocash/nerocash/master/share/pixmaps/nerocash128.png
+      install -m 0644 -D -t $SNAPCRAFT_PART_INSTALL/share/pixmaps nerocash128.png
     build-packages:
       - wget
     after:
